spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  mail:
    host: localhost
    port: 1025
    username: ali
    password: ali
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        debug: true
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 300000 # 5 min
      refresh-token:
        expiration: 86400000 # 1 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads

